#python preprocess.py --input_video ichao.mp4 --name ichao --target ./example
#python preprocess.py --input_video input_videos/jin_00_test.mp4 --name jin_00 --target ../ViViD/data
python preprocess.py --input_video input_videos/jin_01_test.mp4 --name jin_01 --target ../ViViD/data
python preprocess.py --input_video input_videos/jin_02_test.mp4 --name jin_02 --target ../ViViD/data
python preprocess.py --input_video input_videos/jin_03_test.mp4 --name jin_03 --target ../ViViD/data
python preprocess.py --input_video input_videos/jin_04_test.mp4 --name jin_04 --target ../ViViD/data
python preprocess.py --input_video input_videos/jin_05_test.mp4 --name jin_05 --target ../ViViD/data
python preprocess.py --input_video input_videos/jin_06_test.mp4 --name jin_06 --target ../ViViD/data
python preprocess.py --input_video input_videos/jin_07_test.mp4 --name jin_07 --target ../ViViD/data
python preprocess.py --input_video input_videos/jin_08_test.mp4 --name jin_08 --target ../ViViD/data
python preprocess.py --input_video input_videos/jin_09_test.mp4 --name jin_09 --target ../ViViD/data
python preprocess.py --input_video input_videos/jin_10_test.mp4 --name jin_10 --target ../ViViD/data
python preprocess.py --input_video input_videos/jin_11_test.mp4 --name jin_11 --target ../ViViD/data
python preprocess.py --input_video input_videos/jin_12_test.mp4 --name jin_12 --target ../ViViD/data
python preprocess.py --input_video input_videos/jin_13_test.mp4 --name jin_13 --target ../ViViD/data
python preprocess.py --input_video input_videos/jin_14_test.mp4 --name jin_14 --target ../ViViD/data
python preprocess.py --input_video input_videos/jin_15_test.mp4 --name jin_15 --target ../ViViD/data
python preprocess.py --input_video input_videos/lab_00_test.mp4 --name lab_00 --target ../ViViD/data
python preprocess.py --input_video input_videos/lab_01_test.mp4 --name lab_01 --target ../ViViD/data
python preprocess.py --input_video input_videos/lab_02_test.mp4 --name lab_02 --target ../ViViD/data
python preprocess.py --input_video input_videos/lab_03_test.mp4 --name lab_03 --target ../ViViD/data
python preprocess.py --input_video input_videos/lab_04_test.mp4 --name lab_04 --target ../ViViD/data
python preprocess.py --input_video input_videos/lab_05_test.mp4 --name lab_05 --target ../ViViD/data
python preprocess.py --input_video input_videos/lab_06_test.mp4 --name lab_06 --target ../ViViD/data
python preprocess.py --input_video input_videos/lab_07_test.mp4 --name lab_07 --target ../ViViD/data
python preprocess.py --input_video input_videos/lab_08_test.mp4 --name lab_08 --target ../ViViD/data